stages:
  - build
  - test
  - deploy
  - staging test

build website:
  stage: build
  image: node
  script:
  - npm install
  - npm install -g gatsby-cli
  - gatsby build
  artifacts:
    paths:
      - ./public
  tags:
  - josua

test artifact:
  stage: test
  image: alpine
  script:
    - grep -q "Gatsby" ./public/index.html
  tags:
    - josua

.deploy staging:
  stage: deploy
  image: ruby
  before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  script:
  - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup

deploy staging:
  stage: deploy
  image: kroniak/ssh-client
  when: manual
  allow_failure: false
  environment:
    name: staging
    url: http://$AWS_SERVER
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$AWS_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - scp -r ./public/ ubuntu@$AWS_SERVER:public/
    - ssh -p22 ubuntu@$AWS_SERVER "ls; sudo cp public/* /var/www/html/; sudo rm -rf public/"

test staging:
  image: alpine
  stage: staging test
  only:
    - master
  script:
    - apk add --no-cache curl
    - curl -s "http://$AWS_SERVER" | grep -q "Hi people"
